%-----------------------------------------------------------------------
% Job saved on 25-May-2020 14:47:21 by cfg_util (rev $Rev: 6460 $)
% spm SPM - SPM12 (6685)
% cfg_basicio BasicIO - Unknown
% swe SwE - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.swe.smodel.dir = {'/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3/med_v_hc'};
%%
matlabbatch{1}.swe.smodel.scans = {
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_1.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_2.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_3.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_4.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_5.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_6.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_7.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_8.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_9.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_10.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_11.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_12.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_13.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_14.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_15.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_16.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_17.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_18.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_19.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_20.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_21.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_22.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_23.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_24.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_25.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_26.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_27.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_28.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_29.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_30.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_31.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_32.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_33.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_34.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_35.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_36.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_37.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_38.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_39.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_40.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_41.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_42.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_43.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_44.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_45.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_46.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_47.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_48.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_49.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_50.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_51.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_52.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_53.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_54.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_55.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_56.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_57.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_58.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_59.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_60.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_61.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_62.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_63.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_64.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_65.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_66.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_67.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_68.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_69.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_70.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_71.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_72.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_73.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_74.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_75.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_76.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_77.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_78.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_79.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_80.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_81.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_82.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_83.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_84.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_85.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_86.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_87.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_88.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_89.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_90.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_91.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_92.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_93.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_94.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_95.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_96.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_97.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_98.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_99.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_100.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_101.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_102.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_103.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_104.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_105.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_106.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_107.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_108.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_109.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_110.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_111.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_112.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_113.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_114.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_115.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_116.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_117.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_118.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_119.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_120.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_121.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_122.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_123.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_124.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_125.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_126.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_127.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_128.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_129.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_130.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_131.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_132.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_133.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_134.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_135.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_136.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_137.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_138.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_139.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_140.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_141.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_142.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_143.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_144.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_145.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_146.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_147.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_148.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_149.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_150.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_151.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_152.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_153.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_154.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_155.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_156.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_157.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_158.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_159.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_160.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_161.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_162.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_163.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_164.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_165.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_166.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_167.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_168.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_169.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_170.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_171.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_172.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_173.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_174.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_175.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_176.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_177.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_178.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_179.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_180.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_181.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_182.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_183.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_184.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_185.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_186.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_187.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_188.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_189.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_190.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_191.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_192.nii'
                                   '/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/a3_cor_mat_as_nifti_gmr/scan_193.nii'
                                   };
%%
%%
matlabbatch{1}.swe.smodel.type.modified.groups = [1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  3
                                                  3
                                                  3
                                                  2
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  1
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  2
                                                  2
                                                  2
                                                  3
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  1
                                                  3
                                                  3
                                                  3
                                                  2
                                                  2
                                                  2
                                                  2
                                                  1
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  2
                                                  2
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  2
                                                  1
                                                  1
                                                  1
                                                  2
                                                  2
                                                  2
                                                  1
                                                  2
                                                  2
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  1
                                                  3
                                                  3
                                                  2
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  1
                                                  1
                                                  1
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3
                                                  3];
%%
%%
matlabbatch{1}.swe.smodel.type.modified.visits = [1
                                                  1
                                                  2
                                                  1
                                                  2
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  3
                                                  1
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  1
                                                  2
                                                  3
                                                  1
                                                  2
                                                  3
                                                  1
                                                  1
                                                  3];
%%
matlabbatch{1}.swe.smodel.type.modified.ss = 4;
matlabbatch{1}.swe.smodel.type.modified.dof_mo = 3;
%%
matlabbatch{1}.swe.smodel.subjects = [1
                                      3
                                      3
                                      4
                                      4
                                      5
                                      6
                                      6
                                      6
                                      7
                                      7
                                      7
                                      8
                                      8
                                      8
                                      9
                                      10
                                      10
                                      10
                                      11
                                      11
                                      11
                                      12
                                      13
                                      13
                                      14
                                      14
                                      14
                                      15
                                      16
                                      16
                                      16
                                      17
                                      17
                                      17
                                      18
                                      19
                                      19
                                      19
                                      21
                                      21
                                      21
                                      22
                                      22
                                      22
                                      23
                                      23
                                      24
                                      24
                                      24
                                      25
                                      26
                                      26
                                      26
                                      27
                                      27
                                      28
                                      29
                                      29
                                      29
                                      30
                                      31
                                      31
                                      31
                                      32
                                      32
                                      33
                                      33
                                      34
                                      34
                                      34
                                      35
                                      35
                                      35
                                      36
                                      37
                                      37
                                      37
                                      38
                                      38
                                      38
                                      39
                                      39
                                      39
                                      40
                                      42
                                      42
                                      42
                                      43
                                      43
                                      44
                                      44
                                      45
                                      45
                                      45
                                      46
                                      46
                                      46
                                      47
                                      47
                                      47
                                      48
                                      49
                                      49
                                      49
                                      50
                                      50
                                      50
                                      51
                                      51
                                      51
                                      52
                                      52
                                      52
                                      53
                                      53
                                      53
                                      54
                                      54
                                      55
                                      55
                                      55
                                      56
                                      56
                                      56
                                      57
                                      57
                                      57
                                      58
                                      59
                                      59
                                      59
                                      60
                                      60
                                      60
                                      61
                                      62
                                      62
                                      64
                                      64
                                      64
                                      65
                                      65
                                      65
                                      66
                                      66
                                      67
                                      67
                                      67
                                      68
                                      69
                                      69
                                      70
                                      71
                                      71
                                      71
                                      72
                                      72
                                      72
                                      73
                                      73
                                      73
                                      74
                                      74
                                      74
                                      75
                                      76
                                      77
                                      77
                                      78
                                      78
                                      79
                                      79
                                      79
                                      80
                                      80
                                      80
                                      81
                                      81
                                      82
                                      82
                                      82
                                      83
                                      83
                                      84
                                      84
                                      84
                                      85
                                      85
                                      85
                                      86
                                      87
                                      87];
%%
matlabbatch{1}.swe.smodel.cov = struct('c', {}, 'cname', {});
matlabbatch{1}.swe.smodel.multi_cov.files = {'/projects/kg98/Sid/STAGES/STAGES_fmriprep/analyses/swe_validation/covs_a3.txt'};
matlabbatch{1}.swe.smodel.masking.tm.tm_none = 1;
matlabbatch{1}.swe.smodel.masking.im = 1;
matlabbatch{1}.swe.smodel.masking.em = {''};
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_ss = 4;
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_nB = 9999;
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_SwE = 0;
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_stat.WB_F.WB_F_con = [0 0 0 -1 0 1 1 0 -1 0 0 0 0 0];
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_infType.WB_clusterwise.WB_inputType.WB_img = 0;
matlabbatch{1}.swe.smodel.WB.WB_yes.WB_infType.WB_clusterwise.WB_clusThresh = 0.001;
matlabbatch{1}.swe.smodel.globalc.g_omit = 1;
matlabbatch{1}.swe.smodel.globalm.gmsca.gmsca_no = 1;
matlabbatch{1}.swe.smodel.globalm.glonorm = 1;
